### ISSUE TITLE
use error

### ISSUE THREAD

**Issue by JXBurner** [kionell/osu-parsers#10]
安装后提示osu-parsers/lib/browser.mjs 为起点找不到模块 "osu-classes"

**Comment by JXBurner** [comment]
"dependencies": {
    "osu-classes": "^2.1.2",
    "osu-parsers": "^4.0.0"
  }
  安装了这两个版本

**Comment by kionell** [comment]
> 安装后提示osu-parsers/lib/browser.mjs 为起点找不到模块 "osu-classes"

我需要知道您如何安装模块以及您的项目结构和模块导入是什么样的

**Comment by kionell** [comment]
您也可以尝试在 html 文件中为脚本指定 type="module"

```
<script type="module" src="..."></script>
```

**Comment by JXBurner** [comment]
是通过package.json文件安装的npm依赖

**Comment by JXBurner** [comment]
<img width="294" alt="1681723720730" src="https://user-images.githubusercontent.com/49010070/232443973-df8e79d1-b71f-406d-92ba-79d3e235d719.png">

**Comment by JXBurner** [comment]
<img width="438" alt="1681724061182" src="https://user-images.githubusercontent.com/49010070/232445476-8018dd8b-2e67-4569-82ad-c0a988b177df.png">

**Comment by kionell** [comment]
> <img alt="1681723720730" width="294" src="https://user-images.githubusercontent.com/49010070/232443973-df8e79d1-b71f-406d-92ba-79d3e235d719.png">

我的意思是我仍然不明白你的项目是如何解析 npm 模块的。你的项目中有模块打包器吗？比如 rollup, webpack, esbuild等，你不能那样在浏览器中导入npm模块。您还可以使用 vite.js 作为捆绑项目的最简单方法。

**Comment by kionell** [comment]
> <img alt="1681724061182" width="438" src="https://user-images.githubusercontent.com/49010070/232445476-8018dd8b-2e67-4569-82ad-c0a988b177df.png">

也用下面的代码替换你的代码

```
const beatmap: Beatmap = BeatmapDecoder.decode(osuData);
```

```
const decoder = new BeatmapDecoder();
const beatmap = decoder.decodeFromString(osuData);
```
