### ISSUE TITLE
mania beatmap encoding columns are broken

### ISSUE THREAD

**Issue by Sebola3461** [kionell/osu-parsers#19]
We can't encode osu!mania beatmaps (with and without any changes) because it can't determine the columns of note

![image](https://github.com/kionell/osu-parsers/assets/62405013/40980b6d-a7cd-4a01-b70d-90ba90d0a43c)

but it's returning start position
![image](https://github.com/kionell/osu-parsers/assets/62405013/4abbaad0-a1f2-4d58-bef1-a147619441e7)

**Comment by kionell** [comment]
Fixed in #20
