### ISSUE TITLE
bpm calculation wrong

### ISSUE THREAD

**Issue by KenZync** [kionell/osu-parsers#22]
https://osu.ppy.sh/beatmaps/1595714

Difficulty[7K] SV
 
Got : 76.31577943213429
Osu : 145

**Comment by KenZync** [comment]
![image](https://github.com/kionell/osu-parsers/assets/18224778/5a1a57fa-6deb-43ce-8541-df582bbdf9c1)

**Comment by KenZync** [comment]
you have used longest bpm that used rather than divide all of usage

**Comment by KenZync** [comment]
![image](https://github.com/kionell/osu-parsers/assets/18224778/638bef08-1ae2-434a-9584-bccd24645f85)

**Comment by kionell** [comment]
Should be easy to fix. I'll take a look when I get home

**Comment by KenZync** [comment]
i did it by adding up duration for each bpm 

![image](https://github.com/kionell/osu-parsers/assets/18224778/6024e957-5356-4068-b40d-aa39e56668e5)
![image](https://github.com/kionell/osu-parsers/assets/18224778/0700a3fb-f2ba-469b-8609-fd7f70d26140)
![image](https://github.com/kionell/osu-parsers/assets/18224778/2b883089-457a-4f7e-9c71-84c757fab7a5)
