### ISSUE TITLE
Storyboard parser fails on commands with an empty end time

### ISSUE THREAD

**Issue by blueberrymuffin3** [kionell/osu-parsers#3]
Example Map: https://osu.ppy.sh/beatmapsets/653534#osu/1464026

The offending lines look like this:
https://gist.github.com/blueberrymuffin3/fd924a80054a129231f91651d1a42788#file-panda-eyes-ily-m-a-r-v-o-l-l-o-light-insane-osu-L48-L70
```
 M,0,454,,117,104
```

These commands are correctly parsed by osu!stable and osu!lazer as zero-duration commands, but are ignored by `StoryboardParser`.
It's also [referenced in the osu!wiki here](https://osu.ppy.sh/wiki/en/Storyboard/Scripting/Shorthand#start-and-end-times-are-the-same).

The error occurs here:
https://github.com/kionell/osu-parsers/blob/788de925df9f02d2cfd752fba8e95682670523a9/src/Utils/Parsing.ts#L29-L31
It's caused by this line:
https://github.com/kionell/osu-parsers/blob/788de925df9f02d2cfd752fba8e95682670523a9/src/Decoders/Handlers/Storyboards/StoryboardDataDecoder.ts#L252
And is caught here:
https://github.com/kionell/osu-parsers/blob/788de925df9f02d2cfd752fba8e95682670523a9/src/Decoders/StoryboardDecoder.ts#L125-L131

**Comment by blueberrymuffin3** [comment]
I'll probably create a PR for this in a couple days

**Comment by kionell** [comment]
I wanted to rework storyboard decoder for a long time because it hasn't been updated since the first release. I'll do it myself so you don't have to worry about it.

**Comment by kionell** [comment]
I have finally finished this rework. It took a while to rewrite and fix all this stuff.
