### ISSUE TITLE
Add support for browser environment

### ISSUE THREAD

**Issue by kionell** [kionell/osu-parsers#4]
There are some parts of the code that don't work in the browser:
1. All decodeFromPath and encodeToPath methods - fs module problem.
2. Both score decoder and encoder - buffer methods.

**Comment by blueberrymuffin3** [comment]
I'm not sure if this would work, but [conditional exports](https://nodejs.org/api/packages.html#nested-conditions) might allow you to produce a build for browsers/bundlers and a build for node.js
