### ISSUE TITLE
Slider duration is returning NaN

### ISSUE THREAD

**Issue by Sebola3461** [kionell/osu-parsers#7]
There's nothing to explain, it just...
![image](https://user-images.githubusercontent.com/62405013/200127643-309451e8-f54a-4558-accd-f9d9f06dde89.png)

**Comment by kionell** [comment]
Can you send me beatmap ID or .osu file so I can debug it?

**Comment by Sebola3461** [comment]
any beatmap

**Comment by kionell** [comment]
> any beatmap

I can't reproduce it

![image](https://user-images.githubusercontent.com/43014304/200136904-c240a84d-95e8-42fc-ba5b-9659a4c11275.png)

**Comment by Sebola3461** [comment]
weird, cuz i just parsed a map and it returned NaN

**Comment by Sebola3461** [comment]
detail: I parsed the map using `decodeFromString` method

**Comment by kionell** [comment]
> weird, cuz i just parsed a map and it returned NaN

What beatmap tho?

**Comment by Sebola3461** [comment]
> > weird, cuz i just parsed a map and it returned NaN
> 
> What beatmap tho?

582543 (beatmapset)

**Comment by kionell** [comment]
Try to update [osu-classes](https://github.com/kionell/osu-classes) and osu-parsers. I think it's most likely a version conflict

**Comment by Sebola3461** [comment]
I fixed! It was a ipc module configuration (i'm running in electron). Sorry for that.

**Comment by kionell** [comment]
Aight
